export const SECURITY_CHECK_CATALOG = [
  { id: "rls", name: "Missing RLS", engine: "core" },
  { id: "unauthenticated_write", name: "Unauthenticated database writes", engine: "core" },
  { id: "service_role_client", name: "Client-side service_role reference", engine: "core" },
  { id: "unprotected_rpc", name: "Unprotected SECURITY DEFINER", engine: "core" },
  { id: "committed_env_file", name: "Committed .env file", engine: "core" },
  { id: "hardcoded_secret", name: "Hardcoded Stripe/AWS/API secrets", engine: "core" },
  { id: "cors_wildcard", name: "CORS wildcard", engine: "core" },
  { id: "fake_env_example", name: "Real credentials in env templates", engine: "core" },
  { id: "rls_policy_missing", name: "RLS enabled without visible policy", engine: "extended" },
  { id: "sql_grant_public", name: "SQL privileges granted to PUBLIC", engine: "extended" },
  { id: "sql_grant_anon", name: "SQL privileges granted to anon", engine: "extended" },
  { id: "storage_public", name: "Public Supabase Storage bucket", engine: "extended" },
  { id: "storage_policy_broad", name: "Broad storage.objects policy", engine: "extended" },
  { id: "sql_execute_public", name: "Function executable by PUBLIC/anon", engine: "extended" },
  { id: "security_definer_search_path", name: "SECURITY DEFINER search_path risk", engine: "extended" },
  { id: "hardcoded_jwt_secret", name: "Hardcoded JWT signing secret", engine: "extended" },
  { id: "google_api_key", name: "Google API key", engine: "extended" },
  { id: "github_token", name: "GitHub access token", engine: "extended" },
  { id: "private_key", name: "Committed private key", engine: "extended" },
  { id: "database_url", name: "Credential-bearing database URL", engine: "extended" },
  { id: "hardcoded_password", name: "Hardcoded password", engine: "extended" },
  { id: "hardcoded_bearer", name: "Hardcoded bearer token", engine: "extended" },
  { id: "sendgrid_key", name: "SendGrid API key", engine: "extended" },
  { id: "twilio_token", name: "Twilio credential", engine: "extended" },
  { id: "slack_token", name: "Slack token", engine: "extended" },
  { id: "npm_token", name: "npm access token", engine: "extended" },
  { id: "vercel_token", name: "Vercel token", engine: "extended" },
  { id: "netlify_token", name: "Netlify token", engine: "extended" },
  { id: "child_process_exec", name: "OS command execution API", engine: "extended" },
  { id: "eval_usage", name: "eval()", engine: "extended" },
  { id: "function_constructor", name: "Function constructor", engine: "extended" },
  { id: "innerhtml_assignment", name: "innerHTML assignment", engine: "extended" },
  { id: "dangerous_html", name: "React dangerouslySetInnerHTML", engine: "extended" },
  { id: "document_write", name: "document.write", engine: "extended" },
  { id: "postmessage_wildcard", name: "postMessage wildcard origin", engine: "extended" },
  { id: "open_redirect", name: "Request-controlled redirect", engine: "extended" },
  { id: "cors_all_origins", name: "Wildcard CORS origin", engine: "extended" },
  { id: "cookie_missing_httponly", name: "Cookie without HttpOnly", engine: "extended" },
  { id: "cookie_insecure", name: "Cookie Secure disabled", engine: "extended" },
  { id: "cookie_samesite_none", name: "SameSite=None cookie", engine: "extended" },
  { id: "http_url", name: "Insecure HTTP URL", engine: "extended" },
  { id: "debug_endpoint", name: "Debug/internal/admin endpoint", engine: "extended" },
  { id: "wildcard_dependency", name: "Unbounded dependency version", engine: "extended" },
  { id: "git_dependency", name: "Git-based dependency", engine: "extended" },
  { id: "npmrc_token", name: "Committed npm credential", engine: "extended" },
  { id: "docker_socket", name: "Docker socket mount", engine: "extended" },
  { id: "weak_hash", name: "Weak MD5/SHA-1 usage", engine: "extended" },
  { id: "weak_random", name: "Math.random for sensitive values", engine: "extended" },
  { id: "path_traversal", name: "Request-controlled filesystem path", engine: "extended" },
  { id: "command_injection", name: "Request-controlled command execution", engine: "extended" },
] as const;

export const TOTAL_SECURITY_CHECKS = SECURITY_CHECK_CATALOG.length;
